services:
  db:
    container_name: db
    build: docker/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/db_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 2s
      retries: 5

  service:
    container_name: service
    build: 
      dockerfile: docker/dyna/Dockerfile
      context: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9001:9001"
    environment:
      - CONFIG_FILE="./config.json"

volumes:
  postgres_data:
